# Tomcat
server:
  servlet:
    context-path: /document
  port: 20020

# Spring
spring:
  application:
    name: zsk-module-document
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import:
      - optional:nacos:application.yml?group=${spring.profiles.active}&refresh=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?group=${spring.profiles.active}&refresh=true
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:192.168.101.129:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:123456}
      discovery:
        namespace: ${NACOS_NAMESPACE:d4cbb030-726e-4d17-92d3-1042063c3bd7}
        group: ${spring.profiles.active}
      config:
        namespace: ${NACOS_NAMESPACE:d4cbb030-726e-4d17-92d3-1042063c3bd7}
        file-extension: yml
        refresh-enabled: true