# Tomcat
server:
  servlet:
    context-path: /auth
  port: 10010

# Spring
spring:
  application:
    name: zsk-auth
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:application.yml?group=${spring.profiles.active}&refresh=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?group=${spring.profiles.active}&refresh=true
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:192.168.101.129:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:123456}
      discovery:
        namespace: ${NACOS_NAMESPACE:d4cbb030-726e-4d17-92d3-1042063c3bd7}
        group: ${spring.profiles.active}
      config:
        namespace: ${NACOS_NAMESPACE:d4cbb030-726e-4d17-92d3-1042063c3bd7}
        file-extension: yml
        refresh-enabled: true
    sentinel:
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD:192.168.101.129:8858}
        port: 8719
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            data-id: ${spring.application.name}-flow-rules
            group-id: ${spring.profiles.active}
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            data-id: ${spring.application.name}-degrade-rules
            group-id: ${spring.profiles.active}
            data-type: json
            rule-type: degrade