# Tomcat
server:
  port: 8080

# Spring
spring:
  main:
    web-application-type: reactive
  application:
    name: zsk-gateway
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:application.yml?group=${spring.profiles.active}&refresh=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?group=${spring.profiles.active}&refresh=true
  cloud:
    nacos:
      server-addr: 192.168.101.129:8848
      username: nacos
      password: 123456
      discovery:
        namespace: d4cbb030-726e-4d17-92d3-1042063c3bd7
        group: ${spring.profiles.active}
      config:
        namespace: d4cbb030-726e-4d17-92d3-1042063c3bd7
        file-extension: yml
        refresh-enabled: true