spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.101.129:3306/zsk_system?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: mysql_Ck2bRf

# About页面配置
about:
  tech-stack:
    - id: java
      name: JAVA
      description: 后端核心开发语言
    - id: mysql
      name: MYSQL
      description: 关系型数据库管理系统
    - id: redis
      name: REDIS
      description: 高性能键值对数据库
    - id: spring
      name: SPRING
      description: 企业级应用开发框架
    - id: docker
      name: DOCKER
      description: 容器化部署与管理
    - id: rocketmq
      name: ROCKETMQ
      description: 分布式消息中间件
    - id: react
      name: REACT
      description: 构建用户界面的前端库
    - id: ts
      name: TS
      description: JavaScript 的超集
  faq:
    - title: 使用操作类
      items:
        - id: "1"
          question: 如何导入本地 Markdown 文件？
          answer: 在文档编辑器页面，直接将本地 .md 文件拖拽至编辑区域即可自动解析并导入内容。
        - id: "2"
          question: 支持哪些视频格式上传？
          answer: 目前支持 MP4、WebM、MOV 等主流视频格式。
    - title: 功能适配类
      items:
        - id: "3"
          question: 移动端可以使用编辑器吗？
          answer: 可以。移动端编辑器针对触屏操作进行了优化。
        - id: "4"
          question: 如何开启深色模式？
          answer: 点击右上角的系统设置图标，在"主题风格"中选择"深色"或"跟随系统"。

# 简历配置
resume:
  modules:
    - id: basic
      type: basic
      title: 基本信息
      icon: user
      isDeletable: false
      isVisible: true
      data:
        name: 张三
        jobIntention: Java开发工程师
        age: 28
        gender: 男
        city: 北京
        phone: 138****8888
        email: zhangsan@example.com
        github: https://github.com/zhangsan
        summary: 5年Java开发经验，熟悉Spring Cloud微服务架构
        avatar: /avatar/default.jpg
        experience: 5年
        salary: 20-30K
        politics: 群众
        status: 随时入职
    - id: experience
      type: content
      title: 工作经历
      icon: briefcase
      isDeletable: true
      isVisible: true
      content: <h3>某科技公司</h3><p>2020.06 - 至今</p><p>负责核心业务系统开发...</p>
    - id: education
      type: content
      title: 教育背景
      icon: graduation-cap
      isDeletable: true
      isVisible: true
      content: <h3>某大学</h3><p>2016.09 - 2020.06</p><p>计算机科学与技术专业</p>

# 工具箱配置
toolbox:
  tools:
    - id: json-formatter
      title: JSON格式化工具
      description: 在线JSON格式化、压缩、校验工具
      logo: /tools/json.png
      tags:
        - JSON
        - 格式化
        - 开发工具
      url: /tools/json-formatter
      images:
        - /images/tools/json-1.png
        - /images/tools/json-2.png
      features:
        - JSON格式化美化
        - JSON压缩
        - JSON校验
        - 语法高亮
      stats:
        views: 10000
        likes: 500
        usage: 8000
      author:
        name: 开发团队
        avatar: /avatar/default.png
      createAt: 2026-01-01
    - id: base64-converter
      title: Base64编解码工具
      description: 在线Base64编码解码转换工具
      logo: /tools/base64.png
      tags:
        - Base64
        - 编码
        - 解码
      url: /tools/base64
      images:
        - /images/tools/base64-1.png
      features:
        - Base64编码
        - Base64解码
        - 支持中文
      stats:
        views: 5000
        likes: 200
        usage: 3000
      author:
        name: 开发团队
        avatar: /avatar/default.png
      createAt: 2026-01-15
    - id: timestamp-converter
      title: 时间戳转换工具
      description: 在线时间戳与日期格式互相转换
      logo: /tools/timestamp.png
      tags:
        - 时间戳
        - 日期
        - 转换
      url: /tools/timestamp
      images:
        - /images/tools/timestamp-1.png
      features:
        - 时间戳转日期
        - 日期转时间戳
        - 支持毫秒秒级
      stats:
        views: 8000
        likes: 300
        usage: 6000
      author:
        name: 开发团队
        avatar: /avatar/default.png
      createAt: 2026-01-20