# 网关配置
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            # 认证中心
            - id: zsk-auth
              uri: lb://zsk-auth
              predicates:
                - Path=/auth/**
            # 系统模块
            - id: zsk-system
              uri: lb://zsk-system
              predicates:
                - Path=/system/**


security:
  # XSS 防护配置
  xss:
    enabled: true
    exclude-urls:
      - /system/notice/*
  # 安全配置 (白名单)
  ignore:
    whites:
      - /auth/login
      - /auth/register
      - /auth/logout
      - /auth/captcha
      - /auth/email/code
      - /auth/third/**
      - /auth/test/hello
      - /system/user/info/*